name: bootcamp build

on:
  pull_request:
    paths:
      - '.github/workflows/bootcamp-build.yml'
      - 'bootcamp/Dockerfile'
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./bootcamp/Dockerfile
        push: false
        tags: gqcg/bootcamp:latest
